<a href="https://colab.research.google.com/github/andersonmoraix/analisedeconjuntura_anotacoes/blob/main/aula06_analisedonovoCAGED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CURSO: Análise de Conjuntura usando Python - Análise Macro<br>
AULA: Coleta e tratamento de dados do CAGED com Python<br>
INFORMAÇÕES: saiba mais sobre o CAGED (MTE) no link http://pdet.mte.gov.br/novo-caged <br>
AUTOR: Fernando da Silva/Cientista de dados

# Bibliotecas

In [ ]:
# Instalar bibliotecas
!pip install ipeadatapy

# Importar bibliotecas
import ipeadatapy as ipea
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ipeadatapy
  Downloading ipeadatapy-0.1.7-py3-none-any.whl (9.8 kB)
Installing collected packages: ipeadatapy
Successfully installed ipeadatapy-0.1.7

# Dados

In [ ]:
# Obter metadados
metadados = ipea.metadata() #para saber todos códigos do IPEADATA
metadados

,CODE,NAME,COMMENT,LAST UPDATE,BIG THEME,SOURCE ACRONYM,SOURCE,SOURCE URL,FREQUENCY,MEASURE,UNIT,SERIES STATUS,THEME CODE,COUNTRY,NUMERICA
0,ABATE_ABPEAV,Abate - aves - peso das carcaças,O abate de animais é mensurado por sua quantid...,2022-06-09T17:54:02.11-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
1,ABATE_ABPEBV,Abate - bovinos - peso das carcaças,O abate de animais é mensurado por sua quantid...,2022-06-09T17:10:01.89-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
2,ABATE_ABPESU,Abate - suínos - peso das carcaças,O abate de animais é mensurado por sua quantid...,2022-06-09T17:42:02.033-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
3,ABATE_ABQUAV,Abate - aves - quantidade,O abate de animais é mensurado por sua quantid...,2022-06-09T17:42:02.033-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Cabeça,mil,A,1,BRA,True
4,ABATE_ABQUBV,Abate - bovinos - quantidade,O abate de animais é mensurado por sua quantid...,2022-06-09T17:54:02.11-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Cabeça,mil,A,1,BRA,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8923,PIBVRAE,PIB Estadual (valor adicionado a preços básico...,O produto interno bruto (PIB) é o total dos be...,2021-11-25T11:32:05-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,Porcentagem,None,None,81,None,True
8924,VPRODPIN,Valor da produção - indústria,Status da Série: Série Interrompida,2021-05-14T14:54:28-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Irregular,"R$ (mil), a preços do ano 1999",None,None,81,None,True
8925,COVID19_CASOS,Casos de COVID19 no dia,"Para os anos de 1997 a 2008 -- Fonte: IBGE, 19...",2020-06-25T17:24:03-03:00,Regional,IPEA,Instituto de Pesquisa Econômica Aplicada,www.ipea.gov.br,Diária,Pessoas,None,None,82,BRA,True
8926,COVID19_CASOSACUM,"Casos de COVID19, acumulados até o dia","Para os anos de 1997 a 2008 -- Fonte: IBGE, 19...",2020-06-25T17:24:04-03:00,Regional,IPEA,Instituto de Pesquisa Econômica Aplicada,www.ipea.gov.br,Diária,Pessoas,None,None,82,BRA,True
8927,COVID19_OBITOSACUM,"Óbitos por COVID19, acumulados até o dia","Para os anos de 1997 a 2008 -- Fonte: IBGE, 19...",2020-06-25T17:24:02-03:00,Regional,IPEA,Instituto de Pesquisa Econômica Aplicada,www.ipea.gov.br,Diária,Pessoas,None,None,82,BRA,True

In [ ]:
# Identificar o código do CAGED
metadados[metadados.NAME.str.contains("Caged")] #procurar dados do CAGED, colocar o "C" maiusculo funcao sensivel a letras minusculas e maiusculas

,CODE,NAME,COMMENT,LAST UPDATE,BIG THEME,SOURCE ACRONYM,SOURCE,SOURCE URL,FREQUENCY,MEASURE,UNIT,SERIES STATUS,THEME CODE,COUNTRY,NUMERICA
6634,ADMISNC,Empregados - admissões - Novo Caged,Os dados referem-se ao total de admissões de e...,2022-08-31T17:33:05.91-03:00,Regional,MTE/Caged,Ministério do Trabalho e Emprego / Cadastro Ge...,www.mte.gov.br,Mensal,Pessoa,None,None,12,BRA,True
6636,CAGED12_ADMISN12,Empregados - admissões - novo Caged,Para empregados consideram-se aqueles contrata...,2022-09-29T12:20:00.543-03:00,Macroeconômico,Min. Economia/SEPRT/Novo Caged,"Ministério da Economia, Secretaria Especial de...",http://pdet.mte.gov.br/novo-caged,Mensal,Pessoa,None,A,12,BRA,True
6638,CAGED12_DESLIGN12,Empregados - demissões - novo Caged,Para empregados consideram-se aqueles contrata...,2022-09-29T12:20:00.543-03:00,Macroeconômico,Min. Economia/SEPRT/Novo Caged,"Ministério da Economia, Secretaria Especial de...",http://pdet.mte.gov.br/novo-caged,Mensal,Pessoa,None,A,12,BRA,True
6640,CAGED12_SALDON12,Empregados - saldo - novo Caged,Para empregados consideram-se aqueles contrata...,2022-09-29T12:20:00.543-03:00,Macroeconômico,Min. Economia/SEPRT/Novo Caged,"Ministério da Economia, Secretaria Especial de...",http://pdet.mte.gov.br/novo-caged,Mensal,Pessoa,None,A,12,BRA,True
6654,DESLIGNC,Empregados - demissões - Novo Caged,Os dados referem-se ao total de demissões de e...,2022-08-31T17:33:11.037-03:00,Regional,MTE/Caged,Ministério do Trabalho e Emprego / Cadastro Ge...,www.mte.gov.br,Mensal,Pessoa,None,None,12,BRA,True

In [ ]:
# Coletar dados
dados_admissoes = ipea.timeseries("CAGED12_ADMISN12") #admiditidos
dados_demissoes = ipea.timeseries("CAGED12_DESLIGN12") #demitidos
dados_saldo = ipea.timeseries("CAGED12_SALDON12") #saldo

dados_saldo.tail()

,YEAR,DAY,MONTH,CODE,RAW DATE,VALUE (Pessoa)
DATE,,,,,,
2022-04-01,2022,1,4,CAGED12_SALDON12,2022-04-01T00:00:00-03:00,196966.0
2022-05-01,2022,1,5,CAGED12_SALDON12,2022-05-01T00:00:00-03:00,277018.0
2022-06-01,2022,1,6,CAGED12_SALDON12,2022-06-01T00:00:00-03:00,277944.0
2022-07-01,2022,1,7,CAGED12_SALDON12,2022-07-01T00:00:00-03:00,218902.0
2022-08-01,2022,1,8,CAGED12_SALDON12,2022-08-01T00:00:00-03:00,278639.0

In [ ]:
# Tratamento de dados
(
    pd.concat([dados_admissoes, dados_demissoes, dados_saldo]) #para empilhar uma tabela em cima da outra
    .pivot(columns = "CODE", values = "VALUE (Pessoa)")
    .reset_index()
    .rename(
        columns = {
            "DATE": "data",
            "CAGED12_ADMISN12": "admissoes",
            "CAGED12_DESLIGN12": "demissoes",
            "CAGED12_SALDON12": "saldo"
            }
        )
).tail()

CODE       data  admissoes  demissoes     saldo
27   2022-04-01  1854557.0  1657591.0  196966.0
28   2022-05-01  1960960.0  1683942.0  277018.0
29   2022-06-01  1898876.0  1620932.0  277944.0
30   2022-07-01  1886537.0  1667635.0  218902.0
31   2022-08-01  2051800.0  1773161.0  278639.0